# from math/gsm8k dapo dynamic_bs.yaml and agent_workflow/config.yaml

experiment_name: webagent
trial_name: trial0

seed: 1
dynamic_bs: false
enable_offload: false
total_train_epochs: 6
tokenizer_path: ${actor.path}

cluster:
  n_nodes: 2
  n_gpus_per_node: 8
  fileroot: /data/hanyang_dev/searchagent/outputs
  name_resolve:
    type: nfs
    nfs_record_root: /data/hanyang_dev/searchagent/outputs/name_resolve

scheduler:
  type: ray

workflow:
  answer_pattern: '\\boxed\{(?P<answer>[^}]*)\}'
  agent:
    llm_client:
      type: openai
      model: ${actor.path}
      retry_policy: 
        max_tries: 1
      default_kwargs:
        temperature: 1.0
        max_completion_tokens: 8192
        top_p: 1.0
        extra_body:
          chat_template_kwargs:
            enable_thinking: true
    parser:
      type: upstream
    max_tokens: 40960
    system_prompt: |
      You are a helpful AI assistant that can use the available tools to find relevant and reliable information to answer questions accurately.
      
      When answering questions:
      1. Think carefully and break down the question. Make assumptions on what you should find out to answer the question before making tool calls. Then, use search and visit tools to find out the informations.
      2. When using search, provide concise keywords as query terms, Remove question words (why, how, does), conjunctions (and, but), and modal verbs (could, would). Keep only nouns, numbers, and technical terms, and provide relevent modifiers (e.g. comparison, 2025(dates), China(locations)).
      3. Do not search the same query multiple times
      4. Always visit webpages provided by search results. Visiting pages not exist in search results are STRICTLY FORBIDDEN.
      5. Use visit tool with goal to confirm search results.
      6. Use visit tool to get relevent information of concepts.
      7. Provide accurate and comprehensive answers based on your search results
      8. Always put your final answer in \boxed{} format

      BEGIN OF EXAMPLE:

      User: In which city, recognized for its historical significance and cultural heritage, did the individual who became a titular member of the Romanian Academy in the late 19th century and later served as a high-ranking official in the Academy's scientific section, complete his high school education before attending the medical faculty of Vienna University?

      
      Assistant:
      To answer the question:
      1. I need to know who is the person refered in this question
      2. I need to know in which city did the person completed his high school education
      3. I need to provide the city's name as the answer

      Fisrt, I need to indentify the person:
      1. Who became as a titular member of the Romanian Academy in the late 19th century
      2. Did any of the members served as a high-ranking official in the Academy's scientific section
      3. Did any of the members attended the medical faculty of Vienna University?
      
      After finding out who the person is, I need to indentify the city:
      1. Where did the person complete his high school?
      2. Is the city recognized for its historical significance and cultural heritage?

      Finally, after indentifing the city, I need to verify all the informations and provide the city name as the answer.
      
      To begin with, I need to know who became as a titular member of the Romanian Academy in the late 19th century

      <tool_call>{"name": "search", "arguments": {"query": "Romanian Academy  late 19th century  titular member"}}</tool_call>
      

      Tool: 
      1. [Romanian Academy - Wikipedia](url: https://en.wikipedia.org/wiki/Romanian_Academy): The Romanian Academy is a cultural forum founded in Bucharest, Romania, in 1866. It covers the scientific, artistic and literary domains. The academy has 181 active members who are elected for life. According to its bylaws, the academy's main goals are the


      Assistant:
      ... the page [Romanian Academy - Wikipedia] seens useful, I will use visit tool to try to find the list of titular members in the late 19th century
      
      <tool_call>{"name": "visit", "arguments": {"url": "https://en.wikipedia.org/wiki/Romanian_Academy", "goal": "Find the list of titular members of the Romanian Academy in the late 19th century"}}</tool_call>


      Tool:
      The useful information for query Find the list of titular members of the Romanian Academy in the late 19th century as follows:

      Evidence in page:
      The founding members of the Academy:...
      The Presidents of the Academy:...
      Summary:

      The page only provides list of founding members and presidents of the academy, no titular members provided 


      Assistant:
      Maybe I should find the full list of members of the Romanian Academy

      <tool_call>{"name": "search", "arguments": {"query": "Romanian Academy list of members"}}</tool_call>


      Tool:  
      1. [List of members of the Romanian Academy](https://en.wikipedia.org/wiki/List_of_members_of_the_Romanian_Academy) This is a list of members of the Romanian Academy


      Assistant:
      <tool_call>{"name": "visit", "arguments": {"url": "https://en.wikipedia.org/wiki/List_of_members_of_the_Romanian_Academy", "goal": "Find the list of titular members of the Romanian Academy in the late 19th century"}}</tool_call>


      Tool:
      The useful information for query Find the list of titular members of the Romanian Academy in the late 19th century as follows:

      Evidence in page:
      ...
      Summary:
      The titular members of the Romanian Academy in the late 19th century are:
      Mihail Kogălniceanu, Alexandru Papiu-Ilarian ...


      Assistant:
      ... Now I have the titular members of the Romanian Academy in the late 19th century, I should check:
      2. Did any of the members served as a high-ranking official in the Academy's scientific section
      3. Did any of the members attended the medical faculty of Vienna University?

      <tool_call>{"name": "search", "arguments": {"query": "Mihail Kogălniceanu"}}</tool_call>


      ...(many tool calls & responses)

      
      Assistant:
      ... Now I've identified the person, I need to know in which city did the person completed his high school education ...


      ...(many tool calls & responses)


      Assistant:
      ... I have gathered enough information, putting them together ... Note that the question is asking me about the city, NOT the person ...

      According to my search results, ...
      the answer is \boxed{Prague}

      END OF EXAMPLE
      
      Remember to search thoroughly and provide your final answer clearly within the \boxed{} format. 
    # system_prompt: "You are a helpfule assistant, answer the question with tools.\n\nWhile calling the tools, avoid making identical tool calls that had been called before.\nAvoid making more than 5 tool calls in a single response, but always make more tool calls in the next turn if more information is needed.\n\nYour final answer should be in the following format:\n<answer>{{your succinct, final answer, in a few words}}</answer>\n\n"
    # system_prompt: "You are a information seeking master. Seek information using the tools provided to answer the question.\n\nWhile calling the tools, abey the following rules:\n\n1. Think carefully about next tool call. Query different keywords for more information.\n2. Be parsistant in making different queries to gather as enough information as possible to answer the question.\n3. Always try to make tool calls to verify your assumptions before moving on and before answering.\n\nYour final answer should be in the following format:\n<answer>{{your succinct, final answer, in a few words}}</answer>"
    query_prompt: "{query}"

    max_tokens_prompt_margin: 10240
    max_turn: 10000
    max_turn_prompt: |
      You have now reached the maximum tool call turns you can handle. You should stop making tool calls and, based on all the information above, think again and provide what you consider the most likely answer in the following format:
      \boxed{your final answer, in a few words}
    max_tokens_prompt: |
      You have now reached the maximum context length you can handle. You should stop making tool calls and, based on all the information above, think again and provide what you consider the most likely answer in the following format:
      \boxed{your final answer, in a few words}
    raise_repeat_tool_call: true
    llm_retry_config: null
    tool_retry_config:
      max_tries: 3
      max_time: null
      exceptions:
        - pkg://searcherkit.common.errors:RecoverableError
      giveup: null
      jitter: pkg://backoff:full_jitter
      factor: 1.0
      base: 1.0
    sources:
      - name: elasticsearch
        type: elasticsearch
        hosts: ["http://10.60.101.2:10108"]
        index: enwiki-20260601_qwen3-8b
        search_fields: ["title", "text"]
        es_max_concurrency: 256
        embedding_max_concurrency: 2048
        username: elastic
        password: ${oc.env:ES_PASSWORD}
        title_field: title
        text_field: text
        url_field: url
        fetch_field: url
        highlight: true
        highlight_number_of_fragments: 1
        snippet_chars: 8192
        vector_search_mode: hybrid
        embedding_prefix: |
          Instruct: Given a web search query, retrieve relevant passages that answer the query
          Query:
        embedding_model: /data/hanyang_dev/models/Qwen3-Embedding-8B
        embedding_api_key: api_key
        embedding_base_url: http://${oc.env:MASTER_ADDR}:8004/v1
    tools:
      - type: search
        name: search
        description: Search for more information.
        inputSchema:
          type: object
          properties:
            query:
              type: string
          required:
            - query
          additionalProperties: false
        source: [elasticsearch]
        response_char_limit: null
        raise_argument_validation_error: true

      - type: visit
        name: visit
        description: "Visit webpage and return the summary of the content."
        source:
          - elasticsearch
        inputSchema:
          type: object
          properties:
            url:
              type: string
              description: "The URL of the webpage to visit."
            goal:
              type: string
              description: "The goal of the visit for webpage(s)."
          required:
            - url
            - goal
        argument_mapping:
          url: document_id
        summary_goal_key: goal
        summarizer:
          model: ${actor.path}
          max_chars: 40000
          max_concurrency: 1024
          default_kwargs:
            store: false
            max_completion_tokens: 8192
            extra_body:
              chat_template_kwargs:
                enable_thinking: false
          retry_config: null

eval_workflow:
  answer_pattern: ${workflow.answer_pattern}
  agent:
    llm_client:
      type: openai
      model: ${actor.path}
      retry_policy: null
      default_kwargs:
        temperature: 1.0
        max_completion_tokens: 8192
        top_p: 1.0
        extra_body:
          chat_template_kwargs:
            enable_thinking: true
    parser:
      type: upstream
    max_tokens: ${workflow.agent.max_tokens}
    system_prompt: ${workflow.agent.system_prompt}
    query_prompt: ${workflow.agent.query_prompt}
    max_tokens_prompt_margin: 10240
    max_turn: 1000
    max_turn_prompt: ${workflow.agent.max_turn_prompt}
    max_tokens_prompt: ${workflow.agent.max_tokens_prompt}
    raise_repeat_tool_call: false
    check_visit_in_search_results: false
    llm_retry_config: null
    tool_retry_config:
      max_tries: 3
      max_time: null
      exceptions:
        - pkg://searcherkit.common.errors:RecoverableError
        - pkg://jsonschema:ValidationError
      giveup: null
      jitter: pkg://backoff:full_jitter
      factor: 1.0
      base: 1.0
    sources:
      - name: elasticsearch
        type: elasticsearch
        hosts: ["http://10.60.101.2:10108"]
        index: browsecomp-plus_qwen3-8b
        search_fields: ["title", "text"]
        es_max_concurrency: 256
        embedding_max_concurrency: 2048
        username: elastic
        password: ${oc.env:ES_PASSWORD}
        title_field: title
        text_field: text
        url_field: url
        fetch_field: url
        highlight: true
        highlight_number_of_fragments: 1
        snippet_chars: 8192
        vector_search_mode: hybrid
        embedding_prefix: |
          Instruct: Given a web search query, retrieve relevant passages that answer the query
          Query:
        embedding_model: /data/hanyang_dev/models/Qwen3-Embedding-8B
        embedding_api_key: api_key
        embedding_base_url: http://${oc.env:MASTER_ADDR}:8004/v1

    tools:
      - type: search
        name: search
        description: Search for more information.
        inputSchema:
          type: object
          properties:
            query:
              type: string
          required:
            - query
          additionalProperties: false
        source: [elasticsearch]
        response_char_limit: null
        raise_argument_validation_error: true

      - type: visit
        name: visit
        description: "Visit webpage and return the summary of the content."
        source:
          - elasticsearch
        inputSchema:
          type: object
          properties:
            url:
              type: string
              description: "The URL of the webpage to visit."
            goal:
              type: string
              description: "The goal of the visit for webpage(s)."
          required:
            - url
            - goal
        argument_mapping:
          url: document_id
        summary_goal_key: goal
        summarizer:
          model: ${actor.path}
          max_chars: 40000
          max_concurrency: 1024
          default_kwargs:
            store: false
            max_completion_tokens: 8192
            extra_body:
              chat_template_kwargs:
                enable_thinking: false
          retry_config: null

rollout:
  experiment_name: ${experiment_name}
  backend: sglang:d8
  trial_name: ${trial_name}
  max_concurrent_rollouts: 128 # the concurrency refer to task, not traj
  queue_size: null
  consumer_batch_size: ${train_dataset.batch_size}
  max_head_offpolicyness: 3
  enable_rollout_tracing: false
  scheduling_spec: ${actor.scheduling_spec}
  fileroot: ${cluster.fileroot}
  tokenizer_path: ${tokenizer_path}
  dump_to_file: true
  request_timeout: 10000
  setup_timeout: 1800
  agent:
    agent_cls_path: areal.experimental.openai.proxy.online_agent._OnlineAgent
    mode: inline
    tool_call_parser: qwen
    reasoning_parser: qwen3
    export_style: concat
    chat_template_type: concat
    turn_discount: 1.0
    engine_max_tokens: ${workflow.agent.max_tokens}
    session_timeout_seconds: 10000

gconfig:
  n_samples: 8
  min_new_tokens: 0
  max_new_tokens: ${workflow.agent.llm_client.default_kwargs.max_completion_tokens}
  # max_tokens: 131072
  greedy: false
  temperature: ${workflow.agent.llm_client.default_kwargs.temperature}
  top_p: ${workflow.agent.llm_client.default_kwargs.top_p}

eval_gconfig:
  n_samples: 1
  min_new_tokens: 0
  max_new_tokens: ${eval_workflow.agent.llm_client.default_kwargs.max_completion_tokens}
  # max_tokens: 131072
  greedy: false
  temperature: ${eval_workflow.agent.llm_client.default_kwargs.temperature}
  top_p: ${eval_workflow.agent.llm_client.default_kwargs.top_p}

actor:
  enable_igpo_reward: false
  # enable_tree_training: true
  # pad_to_maximum: true # Must be set to true for tree training
  weight_update_mode: xccl
  backend: fsdp:c4
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  path: /home/jovyan1/Qwen3-8B
  attn_impl: "flash_attention_4"
  init_from_scratch: false
  disable_dropout: true
  gradient_checkpointing: true
  dtype: bfloat16
  mb_spec:
    # max_tokens_per_mb: ${workflow.agent.max_tokens}
    max_tokens_per_mb: 70000
  optimizer:
    type: adam
    lr: 5e-6
    lr_scheduler_type: constant
    gradient_clipping: 1.0
    warmup_steps_proportion: 0
  eps_clip: 0.2
  eps_clip_higher: 0.28
  temperature: ${gconfig.temperature}
  overlong_reward_penalty: false
  kl_ctl: 0.0
  ppo_n_minibatches: 4
  importance_sampling_level: token
  rejection_sampling:
    level: token
    upper: 5.0
    agg: mean
    action: clamp
  # behave_imp_weight_cap: 5.0
  # behave_imp_weight_mode: sequence_mask
  recompute_logprob: true
  use_decoupled_loss: true
  reward_norm:
    mean_level: group
    std_level: group
    group_size: ${gconfig.n_samples}
  adv_norm:
    mean_level: batch
    std_level: batch
  max_new_tokens: ${workflow.agent.llm_client.default_kwargs.max_completion_tokens}
  megatron:
    bridge_type: mbridge
  scheduling_spec:
    - task_type: worker
      port_count: 2
      gpu: 1
      mem: 32
      cmd: python3 -m areal.infra.rpc.rpc_server
      env_vars: 
        SEARCHERKIT_LOG_LEVEL: "WARN"
        SGLANG_ALLOW_OVERWRITE_LONGER_CONTEXT_LEN: "1"
        PYTHONPATH: "${oc.env:PWD}/src:${oc.env:PYTHONPATH,''}"
        PYTORCH_CUDA_ALLOC_CONF: "expandable_segments:True"
        NCCL_NVLS_ENABLE: "0"

ref:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  backend: ${actor.backend}
  path: ${actor.path}
  attn_impl: "flash_attention_4"
  init_from_scratch: false
  dtype: ${actor.dtype}
  mb_spec:
    # max_tokens_per_mb: ${workflow.agent.max_tokens}
    max_tokens_per_mb: 120000
  optimizer: null
  scheduling_strategy:
    type: colocation
    target: actor
  scheduling_spec: ${actor.scheduling_spec}

# SGLang
sglang:
  model_path: ${actor.path}
  random_seed: ${seed}
  skip_tokenizer_init: true
  dtype: ${actor.dtype}
  max_running_requests: null
  context_length: ${workflow.agent.max_tokens}
  mem_fraction_static: 0.9
  attention_backend: fa4
  chunked_prefill_size: 8192
  enable_torch_compile: true
  max_prefill_tokens: ${workflow.agent.max_tokens}

# datasets
train_dataset:
  batch_size: 128
  shuffle: true
  pin_memory: true
  num_workers: 16
  path: /home/jovyan1/ASearcher_en_no-math_Qwen3-8B-reject-sample-clean/ASearcher_en_no-math_Qwen3-8B-reject-sample-clean.jsonl
  type: rl

valid_dataset:
  batch_size: 256
  pin_memory: true
  num_workers: 16
  path: /data/hanyang_dev/datasets/browsecomp_plus_decrypted_qa.jsonl
  type: rl

# Utilities
saver:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: 1
  freq_steps: 32
  freq_secs: null

recover:
  mode: auto
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: 1
  freq_steps: 2
  freq_secs: null

evaluator:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: 1
  freq_steps: 32
  freq_secs: null

stats_logger:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  wandb:
    mode: online
    project: ${experiment_name}
    name: ${trial_name}

perf_tracer:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  enabled: false
  session_tracer:
    enabled: false
