# from math/gsm8k dapo dynamic_bs.yaml and agent_workflow/config.yaml

experiment_name: searchagent
trial_name: trial0

seed: 1
dynamic_bs: false
enable_offload: false
total_train_epochs: 3
tokenizer_path: ${actor.path}

cluster:
  n_nodes: 2
  n_gpus_per_node: 8
  fileroot: /home/jovyan/code/searchagent/outputs/areal/experiments
  name_resolve:
    type: nfs
    nfs_record_root: /home/jovyan/code/searchagent/outputs/areal/name_resolve

scheduler:
  type: ray

workflow:
  agent:
    llm_client:
      type: openai
      model: ${actor.path}
      retry_policy: null
      default_kwargs:
        temperature: 1.0
        max_completion_tokens: 9000
        top_p: 1.0
        extra_body:
          chat_template_kwargs:
            enable_thinking: true
      openai:
        api_key: null
        base_url: null
        concurrency_limit: null
        extra_client_kwargs: null
    parser:
      type: qwen
      target: null
      qwen:
        upstream_parsed: true
        drop_thinking: false
      kwargs: {}
    max_tokens: 65536
    system_prompt: |
      You are a helpful and harmless assistant.
      Answer the given question. You must first conduct step by step reasoning between <thought> and </thought> first every time you get new information.
      If you need external information, call the search tool by returning a JSON object inside <tool_call> tags.
      and it will return the top searched results between <tool_response> and </tool_response>.
      You can search as many times as you want. Break down the user's question into specific sub-questions for searching.
      Check previous search history to ensure new queries are unique.
      If you find no further external knowledge needed, you can directly provide the answer inside <answer> and </answer>, without detailed illustrations.
      For example, <answer> Beijing </answer>.
    query_prompt: "{query}"
    max_tokens_prompt_margin: 11000
    max_turn: 1000
    max_turn_prompt: |
      You have now reached the maximum tool call turns you can handle. You should stop making tool calls and, based on all the information above, think again and provide what you consider the most likely answer in the following format:
      <answer>your final answer, in a few words</answer>
    max_tokens_prompt: |
      You have now reached the maximum context length you can handle. You should stop making tool calls and, based on all the information above, think again and provide what you consider the most likely answer in the following format:
      <answer>your final answer, in a few words</answer>
    raise_repeat_tool_call: true
    max_queries_per_tool_call: 4
    llm_retry_config: null
    tool_retry_config:
      max_tries: 3
      max_time: null
      exceptions:
        - pkg://searchagent.errors:RecoverableError
      giveup: null
      jitter: pkg://backoff:full_jitter
      factor: 1.0
      base: 1.0
    sources:
      - name: elasticsearch
        type: elasticsearch
        hosts: ["http://10.32.34.135:9200"]
        index: browsecomp_plus_qwen3-embedding-8b
        search_fields: ["title", "text"]
        es_max_concurrency: 1024
        embedding_max_concurrency: 2048
        summary_max_concurrency: 1024
        title_field: title
        text_field: text
        url_field: url
        highlight: false
        snippet_chars: 8192
        vector_search_mode: vector
        embedding_prefix: |
          Instruct: Given a web search query, retrieve relevant passages that answer the query
          Query:
        embedding_model: /data/hf/hub/models--Qwen--Qwen3-Embedding-8B/snapshots/1d8ad4ca9b3dd8059ad90a75d4983776a23d44af
        embedding_api_key: api_key
        embedding_base_url: http://10.32.20.11:8004/v1
        search_summary_enabled: true
        summary_max_chars: 120000
        summary_max_tokens: 20000
        summary_model: /data/hf/hub/models--Qwen--Qwen3-8B/snapshots/b968826d9c46dd6066d109eabc6255188de91218
        summary_api_key: api_key
        summary_base_url: http://10.32.20.11:6010/v1
        summary_default_kwargs:
          max_tokens: 1024
          extra_body:
            chat_template_kwargs:
              enable_thinking: false
    tools:
      - type: search
        name: search
        description: Search for more information.
        inputSchema:
          type: object
          properties:
            query_list:
              type: array
              items:
                type: string
              minItems: 1
              maxItems: 4
            top_k:
              type: integer
              minimum: 1
          required:
            - query_list
          additionalProperties: false
        source: elasticsearch
        response_char_limit: null
        raise_argument_validation_error: false

eval_workflow:
  agent:
    llm_client:
      type: openai
      model: ${actor.path}
      retry_policy: null
      default_kwargs:
        temperature: 1.0
        max_completion_tokens: 9000
        top_p: 1.0
        extra_body:
          chat_template_kwargs:
            enable_thinking: true
      openai:
        api_key: null
        base_url: null
        concurrency_limit: null
        extra_client_kwargs: null
    parser:
      type: qwen
      target: null
      qwen:
        upstream_parsed: true
        drop_thinking: true
      kwargs: {}
    max_tokens: ${workflow.agent.max_tokens}
    system_prompt: ${workflow.agent.system_prompt}
    query_prompt: ${workflow.agent.query_prompt}
    max_tokens_prompt_margin: 11000
    max_turn: 1000
    max_turn_prompt: ${workflow.agent.max_turn_prompt}
    max_tokens_prompt: ${workflow.agent.max_tokens_prompt}
    raise_repeat_tool_call: false
    max_queries_per_tool_call: ${workflow.agent.max_queries_per_tool_call}
    llm_retry_config: null
    tool_retry_config:
      max_tries: 3
      max_time: null
      exceptions:
        - pkg://searchagent.errors:RecoverableError
        - pkg://jsonschema:ValidationError
      giveup: null
      jitter: pkg://backoff:full_jitter
      factor: 1.0
      base: 1.0
    sources:
      - name: elasticsearch
        type: elasticsearch
        hosts: ["http://10.32.34.135:9200"]
        index: browsecomp_plus_qwen3-embedding-8b
        search_fields: ["title", "text"]
        es_max_concurrency: 1024
        embedding_max_concurrency: 2048
        summary_max_concurrency: 1024
        title_field: title
        text_field: text
        url_field: url
        highlight: false
        snippet_chars: 8192
        vector_search_mode: vector
        embedding_prefix: |
          Instruct: Given a web search query, retrieve relevant passages that answer the query
          Query:
        embedding_model: /data/hf/hub/models--Qwen--Qwen3-Embedding-8B/snapshots/1d8ad4ca9b3dd8059ad90a75d4983776a23d44af
        embedding_api_key: api_key
        embedding_base_url: http://10.32.20.11:8004/v1
        search_summary_enabled: true
        summary_max_chars: 120000
        summary_max_tokens: 20000
        summary_model: /data/hf/hub/models--Qwen--Qwen3-8B/snapshots/b968826d9c46dd6066d109eabc6255188de91218
        summary_api_key: api_key
        summary_base_url: http://10.32.20.11:6010/v1
        summary_default_kwargs:
          max_tokens: 1024
          extra_body:
            chat_template_kwargs:
              enable_thinking: false
    tools:
      - type: search
        name: search
        description: Search for more information.
        inputSchema:
          type: object
          properties:
            query_list:
              type: array
              items:
                type: string
              minItems: 1
              maxItems: 4
            top_k:
              type: integer
              minimum: 1
          required:
            - query_list
          additionalProperties: false
        source: elasticsearch
        response_char_limit: null
        raise_argument_validation_error: false

rollout:
  experiment_name: ${experiment_name}
  backend: sglang:d8
  trial_name: ${trial_name}
  max_concurrent_rollouts: 128 # the concurrency refer to task, not traj
  queue_size: null
  consumer_batch_size: ${train_dataset.batch_size}
  max_head_offpolicyness: 2
  enable_rollout_tracing: true
  scheduling_spec: ${actor.scheduling_spec}
  fileroot: ${cluster.fileroot}
  tokenizer_path: ${tokenizer_path}
  dump_to_file: true
  request_timeout: 7200
  agent:
    mode: inline
    tool_call_parser: qwen
    reasoning_parser: qwen3
    export_style: concat
    chat_template_type: concat 
    turn_discount: 1.0
    engine_max_tokens: ${workflow.agent.max_tokens}
    session_timeout_seconds: 7200

gconfig:
  n_samples: 8
  min_new_tokens: 0
  max_new_tokens: ${workflow.agent.llm_client.default_kwargs.max_completion_tokens}
  # max_tokens: 131072
  greedy: false
  temperature: ${workflow.agent.llm_client.default_kwargs.temperature}
  top_p: ${workflow.agent.llm_client.default_kwargs.top_p}
  top_k: 20

eval_gconfig:
  n_samples: 1
  min_new_tokens: 0
  max_new_tokens: ${eval_workflow.agent.llm_client.default_kwargs.max_completion_tokens}
  # max_tokens: 131072
  greedy: false
  temperature: ${eval_workflow.agent.llm_client.default_kwargs.temperature}
  top_p: ${eval_workflow.agent.llm_client.default_kwargs.top_p}
  top_k: 20

actor:
  # enable_tree_training: true
  # pad_to_maximum: true # Must be set to true for tree training
  weight_update_mode: xccl
  backend: fsdp:d4c2
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  path: /data/hf/hub/models--Qwen--Qwen3-8B/snapshots/b968826d9c46dd6066d109eabc6255188de91218
  attn_impl: "flash_attention_3"
  init_from_scratch: false
  disable_dropout: false
  gradient_checkpointing: true
  dtype: bfloat16
  mb_spec:
    # max_tokens_per_mb: ${workflow.agent.max_tokens}
    max_tokens_per_mb: 70000
  optimizer:
    type: adam
    lr: 1e-6
    lr_scheduler_type: constant
    gradient_clipping: 1.0
    warmup_steps_proportion: 0.001
  eps_clip: 0.2
  eps_clip_higher: 0.28
  temperature: ${gconfig.temperature}
  overlong_reward_penalty: false
  kl_ctl: 0.0
  ppo_n_minibatches: 4
  recompute_logprob: true
  use_decoupled_loss: true
  rejection_sampling:
    level: sequence
    action: mask
    metric: ratio
    upper: 5.0
  reward_norm:
    mean_level: group
    std_level: group
    group_size: ${gconfig.n_samples}
  adv_norm:
    mean_level: batch
    std_level: batch
  max_new_tokens: ${workflow.agent.llm_client.default_kwargs.max_completion_tokens}
  scheduling_spec:
    - task_type: worker
      port_count: 2
      gpu: 1
      mem: 32
      cmd: python3 -m areal.infra.rpc.rpc_server
      env_vars:
        SearchAgent_LOG_LEVEL: "WARN"
        SGLANG_ALLOW_OVERWRITE_LONGER_CONTEXT_LEN: "1"
        CUDA_HOME: /data/rubrics/verl/.cuda-toolkit
        CUDA_PATH: /data/rubrics/verl/.cuda-toolkit
        CPATH: /home/jovyan/miniconda3/envs/webagent-train/lib/python3.12/site-packages/nvidia/curand/include
        CPLUS_INCLUDE_PATH: /home/jovyan/miniconda3/envs/webagent-train/lib/python3.12/site-packages/nvidia/curand/include
        LIBRARY_PATH: /home/jovyan/miniconda3/envs/webagent-train/lib/python3.12/site-packages/nvidia/curand/lib:/data/rubrics/verl/.cuda-toolkit/lib64
        LD_LIBRARY_PATH: /home/jovyan/miniconda3/envs/webagent-train/lib/python3.12/site-packages/nvidia/curand/lib:/data/rubrics/verl/.cuda-toolkit/lib64

ref:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  backend: ${actor.backend}
  path: ${actor.path}
  attn_impl: "flash_attention_3"
  init_from_scratch: false
  dtype: ${actor.dtype}
  mb_spec:
    # max_tokens_per_mb: ${workflow.agent.max_tokens}
    max_tokens_per_mb: 70000
  optimizer: null
  scheduling_strategy:
    type: colocation
    target: actor
  scheduling_spec: ${actor.scheduling_spec}

# SGLang
sglang:
  model_path: ${actor.path}
  random_seed: ${seed}
  skip_tokenizer_init: true
  dtype: ${actor.dtype}
  max_running_requests: null
  context_length: ${workflow.agent.max_tokens}
  mem_fraction_static: 0.8
  max_prefill_tokens: ${workflow.agent.max_tokens}

# datasets
train_dataset:
  batch_size: 128
  shuffle: true
  pin_memory: true
  num_workers: 16
  path: /home/jovyan/data/searchagent/ASearcher_en_no-math_Qwen3-8B-reject-sample-clean.jsonl
  type: rl

valid_dataset:
  batch_size: 256
  pin_memory: true
  num_workers: 4
  path: /home/jovyan/data/searchagent/browsecomp_plus_decrypted_qa.jsonl
  type: rl

# Utilities
saver:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: 1
  freq_steps: 16
  freq_secs: null

recover:
  mode: auto
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: 1
  freq_steps: 16
  freq_secs: 3600

evaluator:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: 1
  freq_steps: 16
  freq_secs: null

stats_logger:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  wandb:
    mode: disabled
    project: ${experiment_name}
    name: ${trial_name}
  swanlab:
    mode: cloud
    project: searchagent
    name: zero_query_repeat_align

perf_tracer:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  enabled: false
  session_tracer:
    enabled: false
