[project]
name = "webagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "backoff>=2.2.1",
    "datasets>=4.4.2",
    "openai>=2.15.0",
]

[project.optional-dependencies]
webtools = [
    "bs4>=0.0.2",
    "crawl4ai>=0.7.8",
]
browsecomp-plus = [
    "fastmcp<3",
]

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

[dependency-groups]
dev = [
    "uv>=0.9.24",
]
