# GenericMCPTool configuration
# Class: webagent.tools.tool.GenericMCPTool

target: pkg://webagent.tools:MCPTool
name: null
transport: "sse"
endpoint: http://127.0.0.1:8100/mcp
auth_header: ""
max_concurrency: null
response_char_limit: null
enable_trace_logging: true
raise_on_fatal: true
